services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: twc_db
    ports:
      - 3306:3306
    volumes:
      - ./two_tier_data:/var/lib/mysql
    networks:
      - two-tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  flask-app:
    build:
      context: .
    container_name: flask-app
    environment:
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin
      MYSQL_HOST: mysql
      MYSQL_DB: twc_db
    networks:
      - two-tier
    ports:
      - 5000:5000
    depends_on:
      - mysql
    restart: always
volumes:
  two_tier_data:

networks:
  two-tier:
    
    
